'use strict';
module.exports = {
    async up(queryInterface, Sequelize) {
        return queryInterface.bulkInsert('cars', [
            {
                id: 1,
                car_name: 'Swift',
                description: 'New Maruti Suzuki Swift Ex-Showroom',
                car_thumbnail_path_1: '/images/swift.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Maruti',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '1',
                day_price: '25',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '35',
                car_mileage: '23',
                car_capacity: '5',
                car_color: 'red',
                car_variant_type: 'lxi',
                total_driven: '1000',
                plate_number: 'PFQ 5157',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 2,
                car_name: 'Alto',
                description: 'New Maruti Suzuki Alto Ex-Showroom',
                car_thumbnail_path_1: '/images/alto.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Maruti',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '5',
                day_price: '15',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '20',
                car_capacity: '4',
                car_color: 'red',
                car_variant_type: 'lxi',
                total_driven: '1000',
                plate_number: 'PFQ 5217',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 3,
                car_name: 'Carnival',
                description: 'New Kia Carnival Ex-Showroom',
                car_thumbnail_path_1: '/images/carnival.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Kia',
                build: '',
                year: '2022',
                mode: 'auto',
                user_id: '6',
                day_price: '30',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '40',
                car_mileage: '16',
                car_capacity: '8',
                car_color: 'black',
                car_variant_type: 'vdi',
                total_driven: '3000',
                plate_number: 'PFA 5212',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 4,
                car_name: 'Ciaz',
                description: 'New Maruti Ciaz Ex Show Room',
                car_thumbnail_path_1: '/images/ciaz.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Maruti',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '1',
                day_price: '35',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '23',
                car_capacity: '5',
                car_color: 'blue',
                car_variant_type: 'vxi',
                total_driven: '4000',
                plate_number: 'PAQ 5227',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 5,
                car_name: 'City',
                description: 'New Honda City Ex Show Room',
                car_thumbnail_path_1: '/images/city.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Honda',
                build: '',
                year: '2022',
                mode: 'auto',
                user_id: '2',
                day_price: '30',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'diesel',
                fuel_capacity: '30',
                car_mileage: '20',
                car_capacity: '5',
                car_color: 'silver',
                car_variant_type: 'zdi',
                total_driven: '1300',
                plate_number: 'QAQ 5227',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 6,
                car_name: 'Creta',
                description: 'New Hyundai Creta Ex Show Room',
                car_thumbnail_path_1: '/images/creta.png',
                car_thumbnail_path_2: '',
                brand: 'Hyundai',
                build: '',
                year: '2022',
                mode: 'auto',
                user_id: '7',
                day_price: '50',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'diesel',
                fuel_capacity: '45',
                car_mileage: '17',
                car_capacity: '5',
                car_color: 'black',
                car_variant_type: 'zxi',
                total_driven: '3459',
                plate_number: 'PXI 2142',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 7,
                car_name: 'Cruze',
                description: 'New Chevrolet Cruze Ex Show Room',
                car_thumbnail_path_1: '/images/cruze.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Chevrolet',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '2',
                day_price: '25',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '20',
                car_capacity: '4',
                car_color: 'silver',
                car_variant_type: 'vxi',
                total_driven: '6000',
                plate_number: 'PXE 4312',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 8,
                car_name: 'Elantra',
                description: 'New Hyundai Elantra Ex Show Room',
                car_thumbnail_path_1: '/images/elantra.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Hyundai',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '2',
                day_price: '70',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '20',
                car_capacity: '4',
                car_color: 'white',
                car_variant_type: 'vxi',
                total_driven: '1290',
                plate_number: 'PAZ 8901',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            }, {
                id: 9,
                car_name: 'Ertiga',
                description: 'New Maruti Suzuki Ertiga Ex Show Room',
                car_thumbnail_path_1: '/images/ertiga.png',
                car_thumbnail_path_2: '',
                brand: 'Maruti',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '4',
                day_price: '85',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '20',
                car_capacity: '6',
                car_color: 'lightblue',
                car_variant_type: 'vdi',
                total_driven: '9812',
                plate_number: 'PDI 3252',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 10,
                car_name: 'I20',
                description: 'New Hyundai I20 Ex Show Room',
                car_thumbnail_path_1: '/images/i20.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Hyundai',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '3',
                day_price: '40',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '17',
                car_capacity: '4',
                car_color: 'red',
                car_variant_type: 'sports',
                total_driven: '7891',
                plate_number: 'PFE 3670',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 11,
                car_name: 'Kona',
                description: 'New Hyundai Kona Ex Show Room',
                car_thumbnail_path_1: '/images/kona.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Hyundai',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '3',
                day_price: '45',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '450',
                car_capacity: '5',
                car_color: 'white',
                car_variant_type: 'vdi',
                total_driven: '7892',
                plate_number: 'PER 1278',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 12,
                car_name: 'Seltos',
                description: 'New Kia Seltos Ex Show Room',
                car_thumbnail_path_1: '/images/seltos.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Seltos',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '4',
                day_price: '55',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '18',
                car_capacity: '5',
                car_color: 'red',
                car_variant_type: 'sportz',
                total_driven: '78123',
                plate_number: 'DFE 7652',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 13,
                car_name: 'Santro',
                description: 'New Hyundai Santro Ex Show Room',
                car_thumbnail_path_1: '/images/sentro.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Hyundai',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '4',
                day_price: '25',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '21',
                car_capacity: '5',
                car_color: 'brown',
                car_variant_type: 'lxi',
                total_driven: '8734',
                plate_number: 'LKS 1275',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },
            {
                id: 14,
                car_name: 'Verna',
                description: 'New Hyundai Verna Ex Show Room',
                car_thumbnail_path_1: '/images/verna.jpeg',
                car_thumbnail_path_2: '',
                brand: 'Hyundai',
                build: '',
                year: '2022',
                mode: 'manual',
                user_id: '3',
                day_price: '34',
                current_location: 'Kuala Lumpur',
                is_featured: false,
                fuel_type: 'petrol',
                fuel_capacity: '30',
                car_mileage: '20',
                car_capacity: '4',
                car_color: 'light silver',
                car_variant_type: 'zdi',
                total_driven: '5690',
                plate_number: 'KJI 1254',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),

            },

        ]);
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
    }
};
