'use strict';
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert('customer_address', [
      {
        id: 1,
        customer_id: 1,
        state: 'perak',
        city: 'kuala lumpur',
        pincode: '12378',
        address: 'Kuala Lumpur steet no 2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        customer_id: 1,
        state: 'Kelantan',
        city: 'Kota Bharu',
        pincode: '12378',
        address: 'Kota Bharu Binjai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        customer_id: 2,
        state: 'perak',
        city: 'kuala lumpur',
        pincode: '12378',
        address: 'Kuala Lumpur steet no 2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        customer_id: 2,
        state: 'Kelantan',
        city: 'Kota Bharu',
        pincode: '12378',
        address: 'Kota Bharu Binjai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        customer_id: 3,
        state: 'perak',
        city: 'kuala lumpur',
        pincode: '12378',
        address: 'Kuala Lumpur steet no 2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        customer_id: 3,
        state: 'Kelantan',
        city: 'Kota Bharu',
        pincode: '12378',
        address: 'Kota Bharu Binjai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        customer_id: 4,
        state: 'perak',
        city: 'kuala lumpur',
        pincode: '12378',
        address: 'Kuala Lumpur steet no 2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        customer_id: 4,
        state: 'Kelantan',
        city: 'Kota Bharu',
        pincode: '12378',
        address: 'Kota Bharu Binjai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        customer_id: 5,
        state: 'perak',
        city: 'kuala lumpur',
        pincode: '12378',
        address: 'Kuala Lumpur steet no 2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        customer_id: 5,
        state: 'Kelantan',
        city: 'Kota Bharu',
        pincode: '12378',
        address: 'Kota Bharu Binjai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        customer_id: 6,
        state: 'perak',
        city: 'kuala lumpur',
        pincode: '12378',
        address: 'Kuala Lumpur steet no 2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        customer_id: 6,
        state: 'Kelantan',
        city: 'Kota Bharu',
        pincode: '12378',
        address: 'Kota Bharu Binjai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        customer_id: 7,
        state: 'perak',
        city: 'kuala lumpur',
        pincode: '12378',
        address: 'Kuala Lumpur steet no 2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        customer_id: 7,
        state: 'Kelantan',
        city: 'Kota Bharu',
        pincode: '12378',
        address: 'Kota Bharu Binjai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
