const Sequelize = require('sequelize');
module.exports=sequelize.define('Car',{
    id:{
        type:Sequelize.INTEGER,
        allowNull:false,
        autoIncrement:true,
        primaryKey:true,
      },
      car_name:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      description:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      car_thumbnail_path_1:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      car_thumbnail_path_2:{
        type:Sequelize.STRING,
        allowNull:true,
      },
      brand:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      build:{
        type:Sequelize.STRING,
        allowNull:true,
      },
      year:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      mode:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      user_id:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      day_price:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      current_location:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      is_featured:{
        type:Sequelize.BOOLEAN,
        allowNull:false,
      },
      fuel_type:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      fuel_capacity:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      car_mileage:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      car_capacity:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      car_color:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      car_variant_type:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      total_driven:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      plate_number:{
        type:Sequelize.STRING,
        allowNull:false,
      },
      status:{
        type:Sequelize.BOOLEAN,
        allowNull:false,
      },
      createdAt: {
        type:Sequelize.DATE,
        allowNull:false,
      },
      updatedAt:{
        type:Sequelize.DATE,
        allowNull:false,
      }


});